### ISSUE TITLE
Overflow problem with multiselect container

### ISSUE THREAD

**Issue by wboykinm** [chriswhong/plutoplus#7]
The `<li>` objects overflow the `.well` container.

![screenshot 2015-05-26 08 58 36](https://cloud.githubusercontent.com/assets/735463/7814395/ebec1c8c-038f-11e5-9eed-039c65343160.png)

I found that dropping the `.well` class made it behave correctly, although the CSS was pretty stark:

![screenshot 2015-05-26 10 15 12](https://cloud.githubusercontent.com/assets/735463/7814428/1daced0a-0390-11e5-8497-d10dd80f1f2f.png)

**Comment by chriswhong** [comment]
I am only able to reproduce this if I untick the overflow:auto CSS rule.  Weird.  Is it still happening for you?  What browser and OS was this in?

**Comment by wboykinm** [comment]
Nope - all cleared up now.
